### PR TITLE
Clean up gradle files

### PR DESCRIPTION
**Pull request by TacoTheDank**
I stumbled across this app on IzzySoft's F-Droid repo and found some things that I think can be improved.

-------------

### 1st commit
- Delete unnecessary files (that don't need to be tracked by Git)

### 2nd commit
- Update gradle wrapper to 7.4.2 using Git Bash

### 3rd commit
- Clean up gradle deprecations
- Move versioning from manifest into gradle
- Added debug suffix to debug variant (for easier testing)
- Clean up outdated proguard rules, only use `-dontobfuscate`
- Compile on JDK 11 (supported because of Android Gradle Plugin 7.x and up)
- Exclude unneeded META-INF packaging, which will shrink the app a tiny bit
- Rearrange dependencies and clean up duplicates (there were *four* instances of core-ktx!)
- Update Android Gradle Plugin 7.1.3 -> 7.2.1 ([changelog](https://developer.android.com/studio/releases/gradle-plugin#7-2-0))

### 4th commit
- Remove MultiDex (this is only necessary for versions below Lollipop, which the app doesn't support)

-------------

Thanks!

### CODE REVIEW

**Comment by ericberman** [comment]
Thanks.  I'm going to have to dive in a bit on this because when I try to build your branch, it's not finding SwipeRefreshLayout, and thus isn't building.  Were you able to build this without errors?

**Comment by TacoTheDank** [comment]
Oh, interesting. The only error I got was the missing googleApi key. The missing swiperefreshlayout is a simple fix, though. I'll fix that.

**Comment by ericberman** [comment]
No worries - I'm actually manually doing a bunch of these changes (Thanks!) on my branch because there are other incompatibilities besides swipe-to-refresh - updating some of the other dependencies is breaking Kotlin in weird ways, such as giving me false-positive errors (e.g., I have an exhaustive when statement that it's telling me is...not exhaustive, I have a couple of places where it's expecting a non-null value and complaining when I pass it a value! i.e., with the "!" to assert non-null).  If I don't update those dependencies, everything is fine, so I'm going to just do these incrementally.

The gradle updates may be the hardest piece for me to unpack, partly because android studio doesn't expose a bunch of these files.

**Comment by TacoTheDank** [comment]
Mm, alright. I fixed the SwipeRefreshLayout error (the dependency was missing).

**Comment by TacoTheDank** [comment]
Also, the command I ran was `./gradlew wrapper --gradle-version 7.4.2 --distribution-type bin` in Git Bash. You can independently verify the integrity of these files by running this command on your own machine and then using a file comparison tool (like WinMerge for example) to compare the results between this PR and your machine. You could also just use a hash checker, as that would be easier.

The updated JAR's integrity can be verified through this as well: https://gradle.org/release-checksums/

**Comment by TacoTheDank** [comment]
@ericberman I have not received any such error on my machine. I looked it up though. Try going to `File | Settings | Build, Execution, Deployment | Build Tools | Gradle` on your Android Studio installation. You should have the JDK set to something that says 11 (or default). This may fix the issue.

image

**Comment by TacoTheDank** [comment]
Also, appreciate the partial merge, but it seems you still left out some important things. I'll update the PR.

**Comment by ericberman** [comment]
Oh, I'm not done.  It's just incremental, and I'm making sure it still works at each stage.  I've found that a few components break things if I upgrade; I don't want to be touching functional code for this.  I have more to do to merge these tomorrow.

THANK-YOU so much both for doing this, and for helping me with the merge items!!

**Review by ericberman — APPROVED** [review]
I confess I know absolutely nothing about what's going on in proguard or gradle, but things build OK and run OK, so I'll go with it.  

I *did* need to remove the .debug suffix.  I'm not sure what that buys, but it breaks maps in the debug environment, so I backed it out.

**Comment by ericberman** [comment]
Thank-you for this!!!

**Pull request merged**
